# To learn about this file, go to http://docs.travis-ci.com/user/languages/c/
language: cpp
compiler:
  - gcc
  - clang
install:
  ## Get Simbody.
  - sudo apt-get update
  - sudo apt-get install liblapack-dev liblas-dev
  # Must get a newer gcc so we can compile with C++11.
  # from https://github.com/travis-ci/travis-ci/issues/979.
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  # If compiling with gcc, make sure to use gcc 4.8.
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # Clone Simbody into the Simbody directory. Don't need its history, and
  # only need the master branch.
  - git clone https://github.com/simbody/simbody.git simbody-source --depth 1 --branch master
  - cd simbody-source
  # Configure Simbody.
  - cmake . -DBUILD_EXAMPLES=on -DBUILD_VISUALIZER=off -DSIMBODY_STANDARD_11=on -DCMAKE_INSTALL_PREFIX=../simbody-install
  # Build Simbody.
  - make -j8
  # Test Simbody. TODO potentially unnecessary and confusing?
  - ctest -j8
  # Install Simbody.
  - make -j8 install
  ## Set up OpenSim. Travis already cloned it for us by this point.
  - cd ../
  # TODO BUILD_API_EXAMPLES?
  - cmake . -DSimTK_INSTALL_DIR=simbody-install -DCMAKE_CXX_FLAGS=-Werror
  - make -j8
script:
  - ctest -j8 
